# Generated by Django 5.2.6 on 2025-09-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='newproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
