# Generated by Django 5.2.6 on 2025-09-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_newproject_options_newproject_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newproject',
            options={'ordering': ['created_at']},
        ),
    ]
