# Generated by Django 5.2.6 on 2025-09-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_newproject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newproject',
            options={'ordering': ['-created_at']},
        ),
    ]
