# Generated by Django 5.2.6 on 2025-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('created', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
