# Generated by Django 5.2.6 on 2025-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='preface',
            field=models.TextField(null=True),
        ),
    ]
