# Generated by Django 5.2.6 on 2025-09-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_preface'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogPost',
        ),
    ]
