# Generated by Django 5.2.6 on 2025-09-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_blog_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='topic_image',
            field=models.ImageField(null=True, upload_to='blog_images/'),
        ),
        migrations.CreateModel(
            name='related_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('related_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.blogpost')),
            ],
        ),
    ]
